version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "black"
enabled = true

